repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/prettier/prettier
    rev: 3.3.3
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.3.3']
        files: "\\.(ts|tsx|js|jsx|json|css|md)$"
